name: oltvi_trabajo
description: OLTVI - App del conductor. Centro de comando para trabajar 24/7.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  oltvi_core:
    path: ../oltvi_core
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
